const express = require("express");
const cors = require("cors");

const headerRoute = require("./routes/header");
const megaMenuRoute = require("./routes/megaMenu");
const sliderRoute = require("./routes/slider");
const servicesRoute = require("./routes/services");
const amazingRoute = require("./routes/amazing");
const bannersRoute = require("./routes/banners");
const flashSale = require("./routes/flashSale");
const bannersGridRouter = require("./routes/bannersGrid");
const categoriesRoutes = require("./routes/categories");
const categoryBannersRoutes = require("./routes/categoryBanners");
const brandsRoute = require("./routes/brands");
const promotionalBannersRoute = require("./routes/promotionalBanners");
const productsBasedOnPreferenceRoute = require("./routes/productsBasedOnPreference");
const recommendedProductsRoute = require("./routes/recommendedProducts");
const eyelashEnhancersRoute = require("./routes/eyelashEnhancers");
const proteinRoute = require("./routes/protein");
const bestSellingProductsRoute = require("./routes/bestSellingProducts");
const hottestProductsRoute = require("./routes/hottestProducts");
const footerRoute = require("./routes/footer");
const footerTrustRouter = require("./routes/footerTrust");
const footerAboutRouter = require("./routes/footerAbout");
const footerInfoRoute = require("./routes/footerInfo");
const footerBrandsRoute = require("./routes/footerBrands");
const app = express();

app.use(cors());
app.use(express.json());

app.use("/api/header", headerRoute);
app.use("/api/mega-menu", megaMenuRoute);
app.use("/api/slider", sliderRoute);
app.use("/api/services", servicesRoute);
app.use("/api/amazing", amazingRoute);
app.use("/api/banners", bannersRoute);
app.use("/api/flash-sale", flashSale);
app.use("/api/bannersGrid", bannersGridRouter);
app.use("/api/categories", categoriesRoutes);
app.use("/api/category-banners", categoryBannersRoutes);
app.use("/api/brands", brandsRoute);
app.use("/api/promotional-banners", promotionalBannersRoute);
app.use("/api/products-based-on-preference",productsBasedOnPreferenceRoute);
app.use("/api/recommended-products",recommendedProductsRoute);
app.use("/api/eyelash-enhancers", eyelashEnhancersRoute);
app.use("/api/protein", proteinRoute);
app.use("/api/best-selling-products", bestSellingProductsRoute);
app.use("/api/hottest-products", hottestProductsRoute);
app.use("/api/footer", footerRoute);
app.use("/api/footer-trust", footerTrustRouter);
app.use("/api/footer-about", footerAboutRouter);
app.use("/api/footer/info", footerInfoRoute);
app.use("/api/footer/brands",footerBrandsRoute);
module.exports = app;